### ISSUE TITLE
flexbox-grid ?

### ISSUE THREAD

**Issue by magsout** [cssrecipes/grid#7]
New repo, new lib : flexbox grid ?

**Comment by MoOx** [comment]
Not sure. Maybe this belong where.
Does the API (class names) will be the same ?
What are the breaking changes ?

**Comment by bloodyowl** [comment]
I'd say new lib

**Comment by MoOx** [comment]
bump for my question @magsout :)

**Comment by magsout** [comment]
@MoOx https://gist.github.com/magsout/13d62e43fbc614bec460/revisions

**Comment by MoOx** [comment]
So no major changes from what I see.
Maybe we can provide this as "cssrecipes-grid/flex" ?
What do you think guys ?

**Comment by bloodyowl** [comment]
why not. we should add a lot of modifiers though, for shrink, grow, alignment & other stuff.

**Comment by MoOx** [comment]
yeap !

**Comment by magsout** [comment]
>why not. we should add a lot of modifiers though, for shrink, grow, alignment & other stuff.

oh yeah, thanks to flex ;)

> Maybe we can provide this as "cssrecipes-grid/flex" ?

yes, good idea
